name: GitHub Actions Python and C++ Linting
run-name: Syntax Check
on: [push]

jobs:
  Check-Python-Syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: C/C++ Linter
        uses: cpp-linter/cpp-linter-action@v2.10.0
