name: GitHub Actions Python and C++ Linting
run-name: Syntax Check
on: [push]

jobs:
  Check-Python-Syntax:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v
      - name: Python Linter
        uses: sunnysid3up/python-linter@v0.1-beta.7
      - name: C/C++ Linter
        uses: cpp-linter/cpp-linter-action@v2.10.0
